### ISSUE TITLE
location.reload()

### ISSUE THREAD

**Issue by bradreeder** [FloatingIntegers/twitterish2.0#11]
Currently when we post a new tweet we use location.reload() to reload the current page so that the most recent tweets are shown on the page.

What we could do instead is simply call our function getTweets() (that sends the getTweets request to the server) after every new tweet is posted. This should update the tweets on the page without having to reload the whole page.

Design Suggestion: when the page first loads for the user, just have the login form appear on the page. When they login in hide the login form and show the dashboard section. When a new tweet is posted, if we use getTweets() to update the tweets on the dashboard we won't need to refresh the page and thus they'll never get taken back to the login form.

**Comment by sofiapoh** [comment]
Very good suggestion, very happy to take a look at this tonight/tomorrow!

**Comment by sofiapoh** [comment]
Fixed!
