### ISSUE TITLE
New tweets on top of the page

### ISSUE THREAD

**Issue by sofiapoh** [FloatingIntegers/twitterish2.0#13]
At the moment when you submit your tweet the latest tweet goes to the end of the page and for some people it might seem like it's not updating. Also, we need to limit the amount of tweets displayed.

**Comment by bradreeder** [comment]
Good point! If I recall we're forEaching an array to display the tweets. If we use the reverse method on the array before the forEach then I guess theoretically it'd display the latest tweet first and the oldest last?

**Comment by bradreeder** [comment]
(I can't work out how to find the cat emoji (^._.^)ﾉ )

**Comment by sofiapoh** [comment]
Fixed now, hitting the hay now. Till tomorrow! 

p.s 😸
