### ISSUE TITLE
node modules

### ISSUE THREAD

**Issue by bradreeder** [FloatingIntegers/twitterish2.0#4]
The git ignore will need amending as it seems the node modules have been pushed to github (sorry!).

**Comment by sofiapoh** [comment]
That was my bad! Gitignore works but i didn't pull down before my first mega-commit..

**Comment by bradreeder** [comment]
I've done it plenty of times lol. I just self-merged a pull request that's removed them from github. You've pulled the gitignore now so I guess the issue is closed?
